### ISSUE TITLE
atalk asks on every start for permissions

### ISSUE THREAD

**Issue by streaps** [cmeng-git/atalk-android#9]
Why won't atalk not accept that I don't want to give it access to my location, video, contacts, etc?

Shouldn't it work without any granted permission as a text messaging client?

**Comment by cmeng-git** [comment]
You can try not to grant all the permissions. However aTalk has not been tested for all combination of the permission grant states. Unlike other apk, aTalk does not abort or stop the  use the app when certain permissions are not granted. However I am not sure what will be outcome when you access certain features that require the permission. You can report back to me in case of system crashes for my review.

**Comment by cmeng-git** [comment]
By the way you can set to Do not ask again, then aTalk will not bother you again on your next launch.

Refer to "Android Runtime Permissions Request" for more info
http://atalk.sytes.net/faq.html#feature_05

**Comment by streaps** [comment]
I always get the permissions request even if I cannot set any permissions anymore and cannot check "Do not ask again" anywhere

**Comment by cmeng-git** [comment]
I suspect your aTalk may have been corrupted. Would you be able to clear the aTalk cache and start all over again. You may also try to reset all the permissions in Settings | APPS | aTalk | Permissions.

The "Don't ask again" option is shown, in addition to DENY and ALLOW buttons when the Permission prompt is displayed.

![permission](https://user-images.githubusercontent.com/7959606/40480247-69ee5c5e-5f80-11e8-8b14-7965611fe19d.png)

**Comment by cmeng-git** [comment]
I will take a lot at the source, to see if android 8 has again changed the
way it handles the permissions.

**Comment by cmeng-git** [comment]
resolved in release version 1.3.1

**Comment by licaon-kter** [comment]
Still seeing this in 2.0.3 F-Droid, "PERMANENTLY DENIED" all minus Storage, but on every start I'm harasses by this screen. Please reopen.

**Comment by cmeng-git** [comment]
See comment: https://github.com/cmeng-git/atalk-android/issues/48#issuecomment-524142466

**Comment by licaon-kter** [comment]
Given that I've used other Android apps before aTalk that FAQ explanation is rather FUD. :(

**Comment by cmeng-git** [comment]
I respect you are an experience user and have good knowledge on xmpp client. However not all users have the same experience as you and do required some help at time.

Also the online FAQ is not just for users, but also for my own references.  Even myself is unable to remember every features that have been implemented in aTalk. Just like the recently Permission Grants questions you raised i.e. why one still seeing the prompt even the user has specified Don't ask again. I just do not remember the full feature implementation until I refer to the source.

aTalk supports chat, media calls, audio messages and sending of picture/video captured via camera. These features need min 3 permissions i.e. storage, camera and mic to operate properly. If users do not even want to grant these 3 features, Then I would not encourage user to use aTalk, instead they should go for other clients like conversations and many others that are available in playstore/F-Droid. Why one want to install aTalk with features not required by user, but consumed user device resources.

> Why do you assume my device's Android version is broken?
My apology if any of my previous comment has led you to believe this. I always come with open mind when user reported a problem. I would not preconceived any conclusion without the actual log data. 
This is also the reason why I am requesting two test accounts on your server, so I can look at detail debug log information. The detain debug log are not included in the user debug log file.

**Comment by licaon-kter** [comment]
The issue was already hashed by Google back in Android 6

When Google made Permissions a thing, app devs started to ask for them on first start, making the user (falsely) believe that "the app won't work without them", hence all the work/thought that went into Permissions (privacy mostly) was nullified.

After Google saw this they started to ask the app devs to not do that and ask for Permissions as needed.

Now, I'll reiterate, `I get it, coding "ask for permission as needed" is extra work`, and I know we can check your code since it's open source, but... maybe for that great UX redesign (that will never come?) think and improve this.

Eg.
* App starts, no need for any permission at all (yes, battery optimisation thing needs to pop-up)
* User adds an account, no need for any permission at all
* User sees roster, pop-up Contacts permission
* User messages someone, no need for any NEW permission at all
* User send/receives a file, pop-up Storage permission
* User wants to send a picture, pop-up Camera permission
* User wants to send an audio message/make a call, pop-up Microphone permission
* User wants to send location, pop-up Location permission

Did I miss any?

There are users that don't want to share location ever, that start prompt sounds fishy.
There are users that don't want to take a picture from your app, that start prompt sounds fishy.
The microphone is a touchy point too.
